<?php

namespace Config;

class AdminPages
{
    /**
     * Array of admin pages with their labels, URLs, and optional keywords.
     * Format: 'label' => 'url'
     */
    public static $pages = [
        'Dashboard' => 'admin/dashboard',
        'Hero Content' => 'admin/homepage',
        'Notices' => 'admin/notices',
        'Products & Services' => 'admin/products',
        'Ticker Messages' => 'admin/ticker',
        'Quick Actions' => 'admin/quick-actions',
        'Safety Section' => 'admin/safety-section/edit',
        'Grievance Steps' => 'admin/grievance-steps',
        'Trust Statistics' => 'admin/trust-stats',
        'About Stats' => 'admin/about-stats',
        'Core Values' => 'admin/about-values',
        'Milestones' => 'admin/about-milestones',
        'Board Members' => 'admin/board-members',
        'Management Team' => 'admin/management-team',
        'Awards' => 'admin/awards',
        'Gallery Categories' => 'admin/gallery-categories',
        'Gallery Items' => 'admin/gallery-items',
        'Deposit Settings' => 'admin/deposit-settings/edit',
        'Deposit Cards' => 'admin/deposit-cards',
        'Deposit Quick Links' => 'admin/deposit-quick-links',
        'Deposit Products' => 'admin/deposit-products',
        'Deposit Interest Rates' => 'admin/deposit-interest-rates',
        'Savings Accounts' => 'admin/savings-accounts',
        'Current Accounts' => 'admin/current-accounts',
        'DICGC FAQs' => 'admin/dicgc-faqs',
        'DEAF Steps' => 'admin/deaf-steps',
        'Loan Cards' => 'admin/loan-cards',
        'Loan Products' => 'admin/loan-products',
        'Loan Interest Rates' => 'admin/loan-interest-rates',
        'Service Settings' => 'admin/service-settings/edit',
        'Service Cards' => 'admin/service-cards',
        'Service Charges' => 'admin/service-charges',
        'Insurance Products' => 'admin/insurance-products',
        'Locker Sizes' => 'admin/locker-sizes',
        'Locker FAQs' => 'admin/locker-faqs',
        'Digital Settings' => 'admin/digital-settings/edit',
        'Digital Services' => 'admin/digital-services',
        'Mobile App Features' => 'admin/mobile-features',
        'Mobile Registration Steps' => 'admin/mobile-registration-steps',
        'Mobile FAQs' => 'admin/mobile-faqs',
        'ATM Locations' => 'admin/atm-locations',
        'Block Card Methods' => 'admin/block-card-methods',
        'After‑Block Steps' => 'admin/block-card-after-steps',
        'UPI Benefits' => 'admin/upi-benefits',
        'UPI Safety Tips' => 'admin/upi-safety-tips',
        'UPI Linking Steps' => 'admin/upi-linking-steps',
        'DigiSaathi Categories' => 'admin/digisaathi-categories',
        'DigiSaathi Contacts' => 'admin/digisaathi-contacts',
        'Downloads' => 'admin/downloads',
        'Complaint Escalation Levels' => 'admin/complaint-escalation-levels',
        'Complaint Categories' => 'admin/complaint-categories',
        'RBI Settings' => 'admin/rbi-settings/edit',
        'RBI Topics' => 'admin/rbi-topics',
        'Fair Practice Principles' => 'admin/rbi-fair-practice-principles',
        'Do\'s' => 'admin/rbi-dos',
        'Don\'ts' => 'admin/rbi-donts',
        'Ombudsman Reasons' => 'admin/rbi-ombudsman-reasons',
        'Booklet Topics' => 'admin/rbi-booklet-topics',
        'Integrated Ombudsman Steps' => 'admin/rbi-integrated-steps',
        'FAQ Categories' => 'admin/faq-categories',
        'FAQs' => 'admin/faqs',
        'Accessibility Features' => 'admin/accessibility-features',
        'Privacy Policy Sections' => 'admin/privacy-policy-sections',
        'Sitemap Sections' => 'admin/sitemap-sections',
        'Sitemap Links' => 'admin/sitemap-links',
        'Branches' => 'admin/branches',
        'Careers' => 'admin/careers',
        'Admin Users' => 'admin/users',
        'Roles & Permissions' => 'admin/roles',
        'General Settings' => 'admin/settings/edit',
        'Social Links' => 'admin/social-links',
        'Activity Logs' => 'admin/logs',
    ];
}