<?php

namespace Config;

class PermissionModules
{
    // List of modules (rows in the permission matrix)
    public static $modules = [
        'dashboard' => 'Dashboard',
        'homepage' => 'Homepage Content',
        'alert_banners' => 'Alert Banners',
        'notices' => 'Notices',
        'products' => 'Products',
        'quick_actions' => 'Quick Actions',
        'safety_section' => 'Safety Section',
        'grievance_steps' => 'Grievance Steps',
        'ticker' => 'Ticker Messages',
        'trust_stats' => 'Trust Stats',
        'about_stats' => 'About Stats',
        'about_values' => 'Core Values',
        'about_milestones' => 'Milestones',
        'board_members' => 'Board Members',
        'management_team' => 'Management Team',
        'awards' => 'Awards',
        'gallery_categories' => 'Gallery Categories',
        'gallery_items' => 'Gallery Items',
        'deposit_settings' => 'Deposit Settings',
        'deposit_cards' => 'Deposit Cards',
        'deposit_quick_links' => 'Deposit Quick Links',
        'deposit_products' => 'Deposit Products',
        'deposit_interest_rates' => 'Deposit Interest Rates',
        'savings_accounts' => 'Savings Accounts',
        'current_accounts' => 'Current Accounts',
        'dicgc_faqs' => 'DICGC FAQs',
        'deaf_steps' => 'DEAF Steps',
        'loan_cards' => 'Loan Cards',
        'loan_products' => 'Loan Products',
        'loan_interest_rates' => 'Loan Interest Rates',
        'service_settings' => 'Service Settings',
        'service_cards' => 'Service Cards',
        'service_charges' => 'Service Charges',
        'insurance_products' => 'Insurance Products',
        'locker_sizes' => 'Locker Sizes',
        'locker_faqs' => 'Locker FAQs',
        'digital_settings' => 'Digital Settings',
        'digital_services' => 'Digital Services',
        'mobile_features' => 'Mobile Features',
        'mobile_registration_steps' => 'Mobile Registration Steps',
        'mobile_faqs' => 'Mobile FAQs',
        'atm_locations' => 'ATM Locations',
        'block_card_methods' => 'Block Card Methods',
        'block_card_after_steps' => 'After‑Block Steps',
        'upi_benefits' => 'UPI Benefits',
        'upi_safety_tips' => 'UPI Safety Tips',
        'upi_linking_steps' => 'UPI Linking Steps',
        'digisaathi_categories' => 'DigiSaathi Categories',
        'digisaathi_contacts' => 'DigiSaathi Contacts',
        'downloads' => 'Downloads',
        'complaints' => 'Complaints',
        'escalation_levels' => 'Escalation Levels',
        'complaint_categories' => 'Complaint Categories',
        'rbi_settings' => 'RBI Settings',
        'rbi_topics' => 'RBI Topics',
        'rbi_fair_practice_principles' => 'Fair Practice Principles',
        'rbi_dos' => 'Do\'s',
        'rbi_donts' => 'Don\'ts',
        'rbi_ombudsman_reasons' => 'Ombudsman Reasons',
        'rbi_booklet_topics' => 'Booklet Topics',
        'rbi_integrated_steps' => 'Integrated Steps',
        'faq_categories' => 'FAQ Categories',
        'faqs' => 'FAQs',
        'accessibility_features' => 'Accessibility Features',
        'privacy_policy_sections' => 'Privacy Policy',
        'sitemap_sections' => 'Sitemap Sections',
        'sitemap_links' => 'Sitemap Links',
        'branches' => 'Branches',
        'careers' => 'Career Applications',
        'admin_users' => 'Admin Users',
        'roles_permissions' => 'Roles & Permissions',
        'general_settings' => 'General Settings',
        'social_links' => 'Social Links',
        'activity_logs' => 'Activity Logs',
    ];

    // List of actions (columns in the permission matrix)
    public static $actions = ['view', 'create', 'edit', 'delete', 'import', 'approve', 'print', 'assign'];
}